### ISSUE TITLE
Vitepress translation UI component doesn't appear anywhere using `doc-before` slot

### ISSUE THREAD

**Issue by edimitchel** [vuejs-translations/vitepress-translation-helper#1]
Hi,

I tried to use the translation helper on the French translation but I encounter several issues by trying it:
- the locale on the UI component was inferred from `localeIndex` from site info, but in my case the value is always `root`.
- by adding it in the vitepress config and into the slot `doc-before,` nothing appears, when I tried `aside-bottom` it appears, is `doc-before` the right slot to use?

~~Aside those issues, this tool could be something I was so much wanted for helping translation diff, where ryu-cho have limits when there is conflict.~~
Is there a guide for automatizing the update of translation status?

**Comment by Jinjiang** [comment]
This page might help:
https://github.com/vuejs-translations/guidelines/blob/main/README_ECOSYSTEM.md

also feel free to checkout Pinia and Vue Router which have practiced it already

Thanks.

**Comment by Jinjiang** [comment]
Close since the discussion is not active anymore.
