### ISSUE TITLE
feature request: target only a subdirectory

### ISSUE THREAD

**Issue by cexbrayat** [vuejs-translations/vitepress-translation-helper#2]
Thank you for this tool!

If I understand correctly,`vitepress-translation-helper` currently targets the whole Git repo.
In the case of Vue Test Utils, it would be helpful to only target the `docs` directory when running a comparison.
Is there a way to do this or could that be added as an option?

**Comment by Jinjiang** [comment]
Good point! Will add it in the next version. Thanks.
